### ISSUE TITLE
Decide convention for components

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers-react#24]
How about

- ~No html in views~

- ~Mui components wrapped eg `MuiButton`~ Create a wrapper component if you think it's likely to be reused.

- Layout stuff (Box/Container) not wrapped

- Components for text types? (PageTitle, Body text, ...?)

**Comment by amdwit** [comment]
I like point 1,3 and 4. About wrapping: Not sure if you mean this: eg Create a custom Button component that uses the MuiButton. Then I like that too.

**Comment by lucaslcode** [comment]
Yes, basically what I did for [TextInput](https://github.com/Couchers-org/couchers-react/blob/dev/src/components/TextInput.tsx) and maybe we rename it to `MuiTextField`

**Comment by amdwit** [comment]
I do not think the renaming is needed. What would that add? And what if we later do not want to use the MUITextfield? So that reasons against the MUI prefix. Your Textfield component is a facade. Developers do not need (to a large degree) to know what component library has been used.

**Comment by lucaslcode** [comment]
I guess the main reason is accidentally importing the Mui TextField instead of our component

**Comment by amdwit** [comment]
Yes, I experience that sometimes. But I think it is only when importing for the first time, after that I think the IDE knows what you mean. Maybe CouchersTextfield would be better then. But I really think just Textfield is the best.

**Comment by darrenvong** [comment]
> No html in views
By that do you mean we try to render only custom components we've created (either within the `features` folder or from the `component` library folder) in the page level components? What's the problem with primitive html elements? Just curious as I don't have strong opinions on that either way.

> Mui components wrapped eg `MuiButton`
> I guess the main reason is accidentally importing the Mui TextField instead of our component
Yeah these are good points, maybe we can implement some lint rules that can help us with this as I prefer not to prefix our own components with the name, as imo they should always take priority over external stuff we import.

**Comment by lucaslcode** [comment]
> What's the problem with primitive html elements?

I guess consistency, and it makes it harder to style later, like a magic number.

**Comment by darrenvong** [comment]
> > What's the problem with primitive html elements?
> 
> I guess consistency, and it makes it harder to style later, like a magic number.

Not if we follow some restrictions like using consistent spacing, colours etc through a pre-defined set of tokens. Those would be good conversations to have too once we have more designers/UI/UX people involved.

My only concern is premature abstraction - i.e. each time we need a new element, we'll be pulling things into `components` straight away without fully knowing the appropriate abstractions, as those things don't tend to become clear until we see a couple of usages of it from experience.

**Comment by lucaslcode** [comment]
> through a pre-defined set of tokens

How do you mean?

> those things don't tend to become clear until we see a couple of usages of it from experience

That's a good point!

**Comment by amdwit** [comment]
I also think muicomponents do not need to go behind a facade right away. A good example is the Textfield in the user form: we noticed that we were repeating a lot of code and only the we decided to wrap it. But another good reason to facade is to easily swap out third party libraries. We will be less dependent on them. It is also easier to replace a single component by a component from another lib. https://www.slideshare.net/nzakas/scalable-javascript-application-architecture

**Comment by darrenvong** [comment]
> through a pre-defined set of tokens

How do you mean?

So instead of applying arbitrary px value for things like margin/padding, we follow some consistent scale that goes up, say, in units of 4 as an example. So when you need more space, you'd go up/down units in this custom scale until it looks right. Same thing for colours, so the whole app sticks to a consistent colour palette that way.

It takes a while to get used to but when done right, it removes a lot of inconsistency across the app. Also provides a common language for working with designers, so when they say two text fields should be 3 units apart, you know how much that is without having to second guess by playing around in the dev tools (I'm sure we've all done that before haha)

**Comment by darrenvong** [comment]
Also: https://martinfowler.com/bliki/Yagni.html

I have no problems with building facades but only when we need it :+1: Pretty much every app I worked on gets highly complex because people are aggressively trying to make everything DRY and over-engineer stuff, so I'd like us to be pragmatic here and do things iteratively rather than building things assuming a full design system is in place already.

**Comment by lucaslcode** [comment]
So is what we've got now too much, or just not too many more? I was going to add `<P>`, `<PageTitle>`.

Maybe let's forget about 'No HTML', but how about 'Create a wrapper component if you think it's likely to be reused'

For example, when I wanted the circular progress, I made a wrapper because I imaging it will be used a lot. What I was worried about (perhaps erroneously) is having the same MUI component sprinkled here and there.

**Comment by darrenvong** [comment]
> 'Create a wrapper component if you think it's likely to be reused'

That sounds good to me. I think the `Button` component with the loading state is a good example as it's not just a button with an additional wrapper. Otherwise, seems harmless but it also makes debugging using the React DevTools harder as the component tree gets one level deeper and it adds up quickly!

> I was going to add `<P>`, `<PageTitle>`
I think `PageTitle` should be ok as we'll need it for every page? Or is that not the case? Not sure what benefit `<P>` would add though. What's gonna be in `P`?

**Comment by amdwit** [comment]
> through a pre-defined set of tokens

Material ui supports that. And some libs even responsively manage vertical rhythm. But maybe for now using the rem unit is enough?

**Comment by amdwit** [comment]
> Not sure what benefit <P> would add though. What's gonna be in P?

Probably a Typography component goes in there. The benefit is that we constrain the options for structuring and it is all done in a consequent way.

**Comment by lucaslcode** [comment]
Yes a typography and I hate seeing `<Typography variant="p" component={<p>}>` or whatever every time we want to use it. Or do you think it won't actually come up that much in reality?

**Comment by darrenvong** [comment]
> Yes a typography and I hate seeing `<Typography variant="p" component={<p>}>` or whatever every time we want to use it. Or do you think it won't actually come up that much in reality?

This doesn't seem to be the case from our usage so far. Also I think `Typography` renders `<p>` by default so you won't need to do that (just like how you used it in `UsernameForm`). Looking at their API, are there many props we want to disable/fix its usage? If not, we're just forwarding props and adds an extra layer for no good reasons.

**Comment by amdwit** [comment]
Besides 'usage' there is also best practice which is based on previous experienced usage.

TextBody is a better name than P

**Comment by amdwit** [comment]
The good reasons are: consistency, readability, maintainability and ease of development

**Comment by darrenvong** [comment]
So looking at how we've implemented these facades:

```javascript
function H2(props: TypographyProps) {
  return <Typography {...props} variant="h2" />;
}
```

Looking at this, I'm still not that convinced:
_It's more maintainable_ -  this was probably the strongest reason until I thought about it more. So the idea is if we change how we implement `H2` in future (e.g. stop using Material UI), then this will stop us from having to change other code that uses this library component... except I doubt it will because it's using *the same props* as the underlying Material UI component.

The chances are, if we change its implementation, the API will be different from the one offered by Material UI, which often means two things: we try to retrofit our new code to fit this old API, which will probably lead to more complex code (yuck), or we update its API so all code using this will have to be updated anyway! I don't really see either option helping maintainability as the app grows.

_It's more readable_ than `<Typography variant="h2" />` - sure, when you use it like `<H2>Some title</H2>`. But as soon as you need to use the other props, this only saves you from using one prop so it's questionable it's that much better

_It's more consistent_ than `<Typography variant="h2" />` - we're forwarding props so it has the same consistency as using `Typography` directly as we're duplicating its API minus one prop?

**Comment by amdwit** [comment]
I do not think it is very likely we ever change component library. And if we do I do not think many of the attributes were used. And if so then we see why the facade is so handy as we can remap the attributes in it. With maintainability I referred mainly to when having to change the custom component.

**Comment by amdwit** [comment]
What about best practice? How did other projects handle this in the past? To be clear: I do not want to put mui stuff behind a facade from the beginning. But whenever a programmer decide to do so it is fine with me. It may be clear that the reasons why to use the facade are quite subjective.

**Comment by amdwit** [comment]
Which components are we talking about ? PageTitle, H2 and H3?

**Comment by darrenvong** [comment]
> It may be clear that the reasons from what moment on to use the facade are quite subjective.

Haha for sure based on the discussions we are having now, but it's good that we're thinking about these things. I personally wouldn't mind sacrificing some consistency in the beginning of a project while we're still figuring out how we use these components. Once they become clear then I think we can enforce the consistency.

> Which components are we talking about ? PageTitle, H2 and H3?
I think the `H*` components for me. Lucas' latest PR shows a good example - he wants the style of a h5 but still needs to use a h2 so we don't break HTML semantics. Since our facade is basically an identical wrapper around `Typography`, there's nothing stopping us from doing `<H5 component="h2" />` which I don't think it's any better than using `Typography`. Subjectively speaking, I think it's worst as I think that's now confusing to read. At least `Typography` don't try to hide it's meant to be generic.

We could probably disable this and force styling through classes, but then we lose styling consistency from what the Material UI `h5` styling looks like. But maybe that's an ok tradeoff?

**Comment by lucaslcode** [comment]
What about keeping all 'our' text components, but not allowing prop forwarding. With the logic that if you want to add a prop to change something, either all instances should also change to be consistent, or you want it to be different and therefore it should be a different component (or just use the mui component).

**Comment by amdwit** [comment]
Ok, I will remove the H2 and H3 then.  Done.

**Comment by darrenvong** [comment]
> or you want it to be different and therefore it should be a different component (or just use the mui component)

I think that sounds good for me. In those cases, they can either live in the same page/sub component as the feature if it's one-off, or be inside the feature-based folder instead to make clear it's not meant to be re-used across the project.
