### ISSUE TITLE
How should errors from thunks be handled?

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers-react#27]

**Comment by amdwit** [comment]
It's been some time I have used redux, but I would think that actions can contain an error property. A errorreducer picks the error and puts it in the store. Then a component that is always part of the website shows an message when needed.

**Comment by lucaslcode** [comment]
So somewhere in the store there is an `error`. Any async thunk action clears it, and if it's not empty, then the thunk has returned an error? Also, what about loading state, same thing?

I'm not experienced in redux but it seems like I keep reading "you shouldn't put local state like loading/errors in the redux store" and then the same person demonstrates how to use thunks by putting loading and errors in the store... What do you think @darrenvong?

**Comment by amdwit** [comment]
both errors and loading can be handled websitewide and very specific:
loading: block the website with a spinner or only replace the button just pressed with a spinner.
error: block the website with an error message or show the validation error non blocking next to the textfield
I would start with all errors and loadings handling by website blocking. Later you can go more specific for a better user experience.

**Comment by darrenvong** [comment]
I can see where the contradictions are based on what you said there @lucaslcode! In general, you shouldn't put state in the Redux store unless it's true global state, or state you want to persist page load (i.e. the use of redux-persist in our case). Otherwise, why do we put ourselves through all the indirections of having to trace which action needs to be dispatched and reducer to call when some simple React state does the job?

With everything moving to hooks, rather than using the old school `connect` higher-order component from Redux (it had some perf optimisation that meant this was less of an issue), dumping everything in the Redux store might also mean we have to be more careful about state update, as it _may_ lead to expensive re-renders if we're not careful. Instead, if we use local state/composition more cleverly, only the right things will re-render without much work on our end.

I think this article from the original Redux co-author sums up my sentiment about when to reach for Redux - https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367 - the indirection is not worth it for me when there's no other apparent benefits other than "it's the Redux way" of doing things.

**Comment by lucaslcode** [comment]
The problem is though, I don't see how to keep loading state/errors local when using a thunk, because you don't have access to the Promise, so you can't await anything

**Comment by darrenvong** [comment]
I believe `dispatch(<thunk action>)` actually returns a Promise which resolves/rejects depending on if the thunk resolves/rejects. So you can use that to update local state depending on the result. For parts that don't use Redux, I guess you won't have that problem at all as the API wrappers are also Promise based.

**Comment by lucaslcode** [comment]
Oh I didn't realize dispatch returns a promise! That's easy then.

**Comment by lucaslcode** [comment]
In that case I think I would also prefer to keep errors and loading out of reducers as much as possible.

**Comment by amdwit** [comment]
But beware of having to copy too much boilerplate in the components where you want to use it. I think you still need to catch errors centralised for logging user experience. We could make two top level components for displaying error and loading state. Then per component can be decided to display it more specific.

**Comment by amdwit** [comment]
Could you consider using mobx-state-tree to make all this much easier? Maybe it should go in a separate issue.

**Comment by lucaslcode** [comment]
> too much boilerplate in the components where you want to use it

I can't immediately think of any extra boilerplate from having errors/loading local state vs in the store. How would it be the case?

> consider using mobx-state-tree

I'm a bit reluctant because part of the reason for choosing redux was using something the largest number of people would be familiar with, to help with volunteers. Though I do like MobX (haven't used state tree).

**Comment by amdwit** [comment]
Yes, I also think mobx can be frightening to beginners.

**Comment by amdwit** [comment]
> I can't immediately think of any extra boilerplate from having errors/loading local state vs in the store. How would it be the case?

If handling errors and loading using reducers, no setLoading(true) is needed in the component. Also handling errors can be left out if handled top level.

**Comment by lucaslcode** [comment]
I see. I seems like we should see how we go for now, and reassess this later. I'll close the issue but do reopen if there's anything else to add.
